version: 0.2
phases:
  install:
    runtime-versions:
      nodejs:10
    commands:
      - npm install
  build:
    commands:
      - npm start
artifacts:
  files:
    - '**/*'
  base-directory: 'build'