version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - cd Java/MovieCityApi
  build:
    commands:
      - mvn clean package
artifacts:
  files:
    - '**/*'
  base-directory: 'Java/MovieCityApi/target'
